apiVersion: v1
kind: Service
metadata:
  name: backend-service          # this is the name frontend uses to talk to backend
  namespace: recipevault
spec:
  selector:
    app: backend                 # routes traffic to pods with label app=backend
  ports:
    - protocol: TCP
      port: 5000                 # port other services use to reach backend
      targetPort: 5000           # port the container is actually listening on
  type: ClusterIP                # internal only — not exposed to internet